apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: vibpositive/nginx:v0.0.1
        name: nginx
        ports:
          - containerPort: 80
        resources:
          limits:
            memory: "1Gi"
            cpu: "0.2"
          requests:
            memory: "1Gi"
            cpu: "0.2"